#!/usr/bin/env python3

import sys
from packetfile import pcap, common

f = open(sys.argv[1], "rb")

reader = pcap.PcapReader(f)

while True:
    pkt = reader.read_packet()
    if pkt is None:
        break

    common.print_packetinfo(pkt)
