#!/usr/bin/env python3

"""
Simple program that lists entries in a pcap file.
"""

import sys
from packet import common
from packet.capfile import pcap

f = open(sys.argv[1], "rb")

reader = pcap.PcapReader(f)

for pkt in reader:
    common.print_packetinfo(pkt)
