#!/usr/bin/env python3

# PCPAPU - Packet Capture Processor And Publising Utility

"""
PCPAPU - Packet Capture Processor And Publishing Utility
This module/program contains code used for the interactive tool pcpapu.
Should the tool need to be extended without modifying this file,
it can be imported and extended programatically.
"""
import sys
import argparse

import readline
import code

from packetfile import packetfile

pycon = code.InteractiveConsole(locals=locals())


# Set up the argparse based commandline argument parser.
parser = argparse.ArgumentParser(description="Generate and doctor packet captures.")
parser.add_argument(dest="outpath", help="output file")
parser.add_argument("-i", "--in", dest="inpaths", action="append", required=True, help="Input file")

# Logical program entry point.
if __name__ == "__main__":
    arguments = parser.parse_args(sys.argv)

    pycon.interact()
    
    
