#!/usr/bin/env python3

# PCPAPU - Packet Capture Processor And Publising Utility

"""
PCPAPU - Packet Capture Processor And Publishing Utility
This module/program contains code used for the interactive tool pcpapu.
Should the tool need to be extended without modifying this file,
it can be imported and extended programatically.
"""
import sys
import argparse

import datetime

import readline
import code

from packet import common
from packet.capfile import packetfile

from packet.pipeline.merge import merge

pycon = code.InteractiveConsole(locals=locals())


# Set up the argument parser.
parser = argparse.ArgumentParser(description="Generate and doctor packet captures.")
parser.add_argument(dest="outpath", help="output file")
parser.add_argument("-i", "--in", dest="inpaths", action="append", required=True, help="Input file")
parser.add_argument("-t", "--time-offset", dest="time_offset", action="store", help="Time offset, in Y/M/D H:M:S format.")

# Logical program entry point.
if __name__ == "__main__":
    arguments = parser.parse_args(sys.argv)
    # Open all packet capture files.
    packetfiles = [packetfile.pf_open_read(path) for path in arguments.inpaths]

    packets = list(merge(packetfiles))

    pycon.interact()
    
    
